springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: "jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    tomcat:
      max-active: 12
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
    show-sql: false
  data:
    web:
      pageable:
        default-page-size: 10
server:
  port: 5021
kiqa:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  bcrypt:
    salt: ${BCRYPT_SALT}
